feat: update darwin scripts

diff --git a/home/.chezmoitemplates/script-library b/home/.chezmoitemplates/script-library
--- a/home/.chezmoitemplates/script-library
+++ b/home/.chezmoitemplates/script-library
@@ -1,39 +1,35 @@
-#!/usr/bin/env bash
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+#   @author         :   Chris Burnham
+#   @description    :
+#   @references     :   https://alinex.gitlab.io/bash-lib/libs/log/
+#                       https://github.com/martinburger/bash-common-helpers/blob/master/bash-common-helpers.sh
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 # ╔══════════╦═══════╦═══════════════════════════════════════════════════════════════════════╗
 # ║    id    ║ level ║ usage                                                                 ║
 # ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║   trace  ║   8   ║ Fine-grained information to provide full visibility of application    ║
-# ║          ║       ║ and library behavior.                                                 ║
+# ║   debug  ║   5   ║ * Detailed information to help diagnose, troubleshoot or test.        ║
 # ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║   debug  ║   7   ║ * Detailed information to help diagnose, troubleshoot or test.        ║
+# ║   info   ║   4   ║ * Standard message for normal behavior such as indicating status or   ║
+# ║          ║       ║ that something has occurred.                                          ║
 # ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║   info   ║   6   ║ * Standard message for normal behavior like indicating status or that ║
-# ║          ║       ║ something has occurred.                                               ║
+# ║  warning ║   3   ║ * An unexpected event within the application.                         ║
 # ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║  notice  ║   5   ║                                                                       ║
+# ║  error   ║   2   ║ * A failure of important functionality.                               ║
 # ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║  warning ║   4   ║ * An unexpected event within the application.                         ║
+# ║ critical ║   1   ║ * A critical fault has occurred which causes an abort.                ║
 # ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║   error  ║   3   ║ * A failure of an important functionality.                            ║
-# ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║ critical ║   2   ║                                                                       ║
-# ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║   alert  ║   1   ║ A fault which does not cause an abort. The application may not be     ║
-# ║          ║       ║ able to continue.                                                     ║
-# ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║   fatal  ║   0   ║ * A critical fault has occurred which causes an abort.                ║
-# ╠══════════╬═══════╬═══════════════════════════════════════════════════════════════════════╣
-# ║    off   ║  -1   ║ *No logging will be performed                                         ║
+# ║    off   ║   0   ║ *No logging will be performed                                         ║
 # ╚══════════╩═══════╩═══════════════════════════════════════════════════════════════════════╝
 
 # --------------------------------------------------------------------------------------------------
 #   @description    :   Script Variables
 # --------------------------------------------------------------------------------------------------
-LOG_LEVEL="${LOG_LEVEL:-6}"
+LOG_LEVEL="${LOG_LEVEL:-4}"
 NO_COLOR="${NO_COLOR:-}"    # true = disable color. otherwise autodetected
+LOG_CATEGORY=false
+LOG_CATEGORY_ICON="🌐"
 # ==================================================================================================
-
 
 # --------------------------------------------------------------------------------------------------
 #   @description    :
@@ -47,25 +43,15 @@ function console_log() {
   shift
 
   # shellcheck disable=SC2034
-  local color_log="\\x1b[39m"
-  # shellcheck disable=SC2034
-  local color_trace="\\x1b[95m"
-  # shellcheck disable=SC2034
   local color_debug="\\x1b[34m"
   # shellcheck disable=SC2034
   local color_info="\\x1b[32m"
-  # shellcheck disable=SC2034
-  local color_notice="\\x1b[96m"
   # shellcheck disable=SC2034
   local color_warning="\\x1b[33m"
   # shellcheck disable=SC2034
   local color_error="\\x1b[31m"
   # shellcheck disable=SC2034
-  local color_critical="\\x1b[1;31m"
-  # shellcheck disable=SC2034
-  local color_alert="\\x1b[1;4;7;31m"
-  # shellcheck disable=SC2034
-  local color_fatal="\\x1b[1;4;37;41m"
+  local color_critical="\\x1b[1;4;37;41m"
 
   local colorvar="color_${log_level}"
   local color="${!colorvar:-${color_error}}"
@@ -78,16 +64,20 @@ function console_log() {
     fi
   fi
 
-  # all remaining arguments are to be printed
+  local log_level_block="${color}$(printf "[%9s]" "${log_level}")${color_reset}"
   local log_line=""
-
+  # all remaining arguments are to be printed
   while IFS=$'\n' read -r log_line; do
-    echo -e "$(date -u +"%Y-%m-%d %H:%M:%S UTC") ${color}$(printf "[%9s]" "${log_level}")${color_reset} ${log_line}" 1>&2
+    if test "$LOG_CATEGORY" = false; then
+      echo -e "$(date -u +"%Y-%m-%d %H:%M:%S UTC") ${color}${log_level_block}${color_reset} ${log_line}" 1>&2
+    else
+      local log_category="$(printf "[${LOG_CATEGORY_ICON}%17s]" "${LOG_CATEGORY:0:16}")"
+      echo -e "$(date -u +"%Y-%m-%d %H:%M:%S UTC") ${log_level_block} ${log_category} ${log_line}" 1>&2
+    fi
   done <<< "${@:-}"
 }
 # ==================================================================================================
 
-
 # --------------------------------------------------------------------------------------------------
 #   @description    :   LOG_LEVEL = 5
 #   @globals        :
@@ -95,53 +85,8 @@ function console_log() {
 #   @outputs        :
 #   @returns        :
 # --------------------------------------------------------------------------------------------------
-function log ()  { [[ "${LOG_LEVEL:-0}" -ge 4 ]] && console_log log "${@}"; true; }
+function debug()    { [[ "${LOG_LEVEL:-0}" -ge 5 ]] && console_log debug "${@}"; true; }
 # ==================================================================================================
-
-
-# --------------------------------------------------------------------------------------------------
-#   @description    :   LOG_LEVEL = 8
-#   @globals        :
-#   @arguments      :
-#   @outputs        :
-#   @returns        :
-# --------------------------------------------------------------------------------------------------
-function trace() { [[ "${LOG_LEVEL:-0}" -eq 8 ]] && console_log trace "${@}"; true; }
-# ==================================================================================================
-
-
-# --------------------------------------------------------------------------------------------------
-#   @description    :   LOG_LEVEL = 7
-#   @globals        :
-#   @arguments      :
-#   @outputs        :
-#   @returns        :
-# --------------------------------------------------------------------------------------------------
-function debug() { [[ "${LOG_LEVEL:-0}" -ge 7 ]] && console_log debug "${@}"; true; }
-# ==================================================================================================
-
-
-# --------------------------------------------------------------------------------------------------
-#   @description    :   LOG_LEVEL = 6
-#   @globals        :
-#   @arguments      :
-#   @outputs        :
-#   @returns        :
-# --------------------------------------------------------------------------------------------------
-function info() { [[ "${LOG_LEVEL:-0}" -ge 6 ]] && console_log info "${@}"; true; }
-# ==================================================================================================
-
-
-# --------------------------------------------------------------------------------------------------
-#   @description    :   LOG_LEVEL = 5
-#   @globals        :
-#   @arguments      :
-#   @outputs        :
-#   @returns        :
-# --------------------------------------------------------------------------------------------------
-function notice() { [[ "${LOG_LEVEL:-0}" -ge 5 ]] && console_log notice "${@}"; true; }
-# ==================================================================================================
-
 
 # --------------------------------------------------------------------------------------------------
 #   @description    :   LOG_LEVEL = 4
@@ -150,9 +95,8 @@ function notice() { [[ "${LOG_LEVEL:-0}" -ge 5 ]] && console_log notice "${@}"; 
 #   @outputs        :
 #   @returns        :
 # --------------------------------------------------------------------------------------------------
-function warning() { [[ "${LOG_LEVEL:-0}" -ge 4 ]] && console_log warning "${@}"; true; }
+function info()     { [[ "${LOG_LEVEL:-0}" -ge 4 ]] && console_log info "${@}"; true; }
 # ==================================================================================================
-
 
 # --------------------------------------------------------------------------------------------------
 #   @description    :   LOG_LEVEL = 3
@@ -161,9 +105,8 @@ function warning() { [[ "${LOG_LEVEL:-0}" -ge 4 ]] && console_log warning "${@}"
 #   @outputs        :
 #   @returns        :
 # --------------------------------------------------------------------------------------------------
-function error() { [[ "${LOG_LEVEL:-0}" -ge 3 ]] && console_log error "${@}"; true; }
+function warning()  { [[ "${LOG_LEVEL:-0}" -ge 3 ]] && console_log warning "${@}"; true; }
 # ==================================================================================================
-
 
 # --------------------------------------------------------------------------------------------------
 #   @description    :   LOG_LEVEL = 2
@@ -172,9 +115,8 @@ function error() { [[ "${LOG_LEVEL:-0}" -ge 3 ]] && console_log error "${@}"; tr
 #   @outputs        :
 #   @returns        :
 # --------------------------------------------------------------------------------------------------
-function critical() { [[ "${LOG_LEVEL:-0}" -ge 2 ]] && console_log critical "${@}"; true; }
+function error()    { [[ "${LOG_LEVEL:-0}" -ge 2 ]] && console_log error "${@}"; true; }
 # ==================================================================================================
-
 
 # --------------------------------------------------------------------------------------------------
 #   @description    :   LOG_LEVEL = 1
@@ -183,22 +125,16 @@ function critical() { [[ "${LOG_LEVEL:-0}" -ge 2 ]] && console_log critical "${@
 #   @outputs        :
 #   @returns        :
 # --------------------------------------------------------------------------------------------------
-function alert() { [[ "${LOG_LEVEL:-0}" -ge 2 ]] && console_log alert "${@}"; true; }
+function critical() { [[ "${LOG_LEVEL:-0}" -ge 1 ]] && console_log critical "${@}"; exit 1; }
 # ==================================================================================================
 
-
 # --------------------------------------------------------------------------------------------------
-#   @description    :   LOG_LEVEL = 0
+#   @description    :
 #   @globals        :
 #   @arguments      :
 #   @outputs        :
 #   @returns        :
 # --------------------------------------------------------------------------------------------------
-function fatal() { [[ "${LOG_LEVEL:-0}" -ge 0 ]] && console_log fatal "${@}"; exit 1; }
-# ==================================================================================================
-
-
-
 function check_binary() {
   if [[ $# -lt 1 ]]; then
     fatal "Missing required argument for function check_binary()"
@@ -218,7 +154,15 @@ function check_binary() {
   # debug "Dependency found: $1"
   return 0
 }
+# ==================================================================================================
 
+# --------------------------------------------------------------------------------------------------
+#   @description    :
+#   @globals        :
+#   @arguments      :
+#   @outputs        :
+#   @returns        :
+# --------------------------------------------------------------------------------------------------
 function check_macos_app() {
   if [[ $# -lt 1 ]]; then
     fatal "Missing required argument for function check_macos_app()"
@@ -232,3 +176,4 @@ function check_macos_app() {
   # debug "Dependency found: $1"
   return 0
 }
+# ==================================================================================================
